apiVersion: skaffold/v2alpha4
kind: Config
metadata:
  name: configuration
build:
  artifacts:
  - image: pingvincible/crud-service
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - app-config.yaml
    - deployment.yaml
    - service.yaml
    - ingress.yaml